### ISSUE TITLE
1 motor stopped working

### ISSUE THREAD

**Issue by B3rt** [AdyRock/com.switchbot#3] opened 2021-04-01 08:16 UTC
Today suddenly 1 motor (achterrraam) stopped working (connected via BLE)

When i try to open or close it using homey nothing happens, it does display and report position, nbattery rsi etc but it refuses to open or close.
When i use the switchbot app then it open or close normally.

I cannot get it to work anymore via Homey BLE connection, also after a while i get a red popup error with a connection timeout report.

Is there a way to get this motor working again in Homey?

Here is an ID from homey for error reporting:
9771be5b-9df0-4777-a415-153e5673acd5

log from settings:

* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Refresh skipped while moving
* Polling BLE: waiting for devices to update
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "c9a09160223b",
  "uuid": "c9a09160223b",
  "address": "c9:a0:91:60:22:3b",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      201,
      160,
      145,
      96,
      34,
      59
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          192,
          95,
          0,
          17
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -69
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "c4f601ae4edb",
  "uuid": "c4f601ae4edb",
  "address": "c4:f6:01:ae:4e:db",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      196,
      246,
      1,
      174,
      78,
      219
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          192,
          45,
          99,
          49
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -62
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "e410773bc5a0",
  "uuid": "e410773bc5a0",
  "address": "e4:10:77:3b:c5:a0",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      228,
      16,
      119,
      59,
      197,
      160
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          208,
          49,
          100,
          17
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -61
}
* Parsed BLE: {
  "id": "c9a09160223b",
  "pid": "c9a09160223b",
  "address": "c9:a0:91:60:22:3b",
  "rssi": -69,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 95,
    "position": 0,
    "lightLevel": 1
  }
}
* Parsed BLE: {
  "id": "c4f601ae4edb",
  "pid": "c4f601ae4edb",
  "address": "c4:f6:01:ae:4e:db",
  "rssi": -62,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 45,
    "position": 99,
    "lightLevel": 3
  }
}
* Parsed BLE: {
  "id": "e410773bc5a0",
  "pid": "e410773bc5a0",
  "address": "e4:10:77:3b:c5:a0",
  "rssi": -61,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 49,
    "position": 100,
    "lightLevel": 1
  }
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "ee8e11e00475",
  "uuid": "ee8e11e00475",
  "address": "ee:8e:11:e0:04:75",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      238,
      142,
      17,
      224,
      4,
      117
    ]
  },
  "serviceData": [],
  "serviceUuids": [],
  "rssi": -65
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "eed0c1f4f4ba",
  "uuid": "eed0c1f4f4ba",
  "address": "ee:d0:c1:f4:f4:ba",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      238,
      208,
      193,
      244,
      244,
      186
    ]
  },
  "serviceData": [],
  "serviceUuids": [],
  "rssi": -66
}
* Parsed BLE: No service data
* Parsed BLE: No service data
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Next BLE polling interval = 10000
* Connecting to BLE device: Achterraam
* Polling BLE
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Refresh skipped while moving
* Polling BLE: waiting for devices to update
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "ee8e11e00475",
  "uuid": "ee8e11e00475",
  "address": "ee:8e:11:e0:04:75",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      238,
      142,
      17,
      224,
      4,
      117
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          192,
          53,
          99,
          49
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -64
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "eed0c1f4f4ba",
  "uuid": "eed0c1f4f4ba",
  "address": "ee:d0:c1:f4:f4:ba",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      238,
      208,
      193,
      244,
      244,
      186
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          192,
          46,
          99,
          17
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -63
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "c4f601ae4edb",
  "uuid": "c4f601ae4edb",
  "address": "c4:f6:01:ae:4e:db",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      196,
      246,
      1,
      174,
      78,
      219
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          192,
          45,
          99,
          49
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -64
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "e410773bc5a0",
  "uuid": "e410773bc5a0",
  "address": "e4:10:77:3b:c5:a0",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      228,
      16,
      119,
      59,
      197,
      160
    ]
  },
  "serviceData": [
    {
      "uuid": "0d00",
      "data": {
        "type": "Buffer",
        "data": [
          99,
          208,
          49,
          100,
          17
        ]
      }
    }
  ],
  "serviceUuids": [
    "cba20d00224d11e69fb80002a5d5c51b"
  ],
  "rssi": -62
}
* Parsed BLE: {
  "id": "ee8e11e00475",
  "pid": "ee8e11e00475",
  "address": "ee:8e:11:e0:04:75",
  "rssi": -64,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 53,
    "position": 99,
    "lightLevel": 3
  }
}
* Parsed BLE: {
  "id": "eed0c1f4f4ba",
  "pid": "eed0c1f4f4ba",
  "address": "ee:d0:c1:f4:f4:ba",
  "rssi": -63,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 46,
    "position": 99,
    "lightLevel": 1
  }
}
* Parsed BLE: {
  "id": "c4f601ae4edb",
  "pid": "c4f601ae4edb",
  "address": "c4:f6:01:ae:4e:db",
  "rssi": -64,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 45,
    "position": 99,
    "lightLevel": 3
  }
}
* Parsed BLE: {
  "id": "e410773bc5a0",
  "pid": "e410773bc5a0",
  "address": "e4:10:77:3b:c5:a0",
  "rssi": -62,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 49,
    "position": 100,
    "lightLevel": 1
  }
}
* {
  "_events": {},
  "_eventsCount": 2,
  "__peripheral": null,
  "__client": {},
  "id": "c9a09160223b",
  "uuid": "c9a09160223b",
  "address": "c9:a0:91:60:22:3b",
  "addressType": "random",
  "connectable": true,
  "manufacturerData": {
    "type": "Buffer",
    "data": [
      89,
      0,
      201,
      160,
      145,
      96,
      34,
      59
    ]
  },
  "serviceData": [],
  "serviceUuids": [],
  "rssi": -62
}
* Parsed BLE: No service data
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Polling BLE: waiting for devices to update
* Next BLE polling interval = 10000

**Comment by AdyRock** [comment] 2021-04-01 09:39
Could you try restarting the app. 
It looks like it is try but failing. There are a few flags to make sure only one thing happens at a time so maybe one has got 'stuck' somehow.

**Comment by AdyRock** [comment] 2021-10-30 10:50
As I have not heard anything I assume the problem is resolved so I will close this issue. Pleas get back to me if you have any other questions.

**Closed by AdyRock** 2021-10-30 10:50 UTC
