### ISSUE TITLE
Switchbot curtains not working anymore: error: INVALID_GRANT

### ISSUE THREAD

**Issue by Thijs1980** [AdyRock/com.switchbot#131] opened 2024-07-28 06:57 UTC
All of my switchbot curtains stopped working and give the same error: INVALID_GRANT when i try to open them via the HomeyPro app.

delete them but cannot connect them again. same error.

thanx in advance

**Comment by L1ttleP00l** [comment] 2024-07-31 19:16
Hello,

I also had a similar incident with the error message: INVALID_GRANT in the context of my air conditioning.

This no longer worked, so I decided to delete the device and integrate it back into Homey. When I get to the Switchbot login page and select my Google account, I get the following message:

“Access blocked: the request for this app is invalid.

You can't log in, because this app has sent an invalid request. You can try again later or contact the developer about this problem. Learn more about this error
If you're one of the developers of this app, see the error details.
Error 400: redirect_uri_mismatch”

Thanks for your help.

![Capture d’écran du 2024-07-31 21-01-24](https://github.com/user-attachments/assets/49e4b0b7-9c77-45c2-8ce9-caf8007e18d0)

**Comment by AdyRock** [comment] 2024-07-31 19:34
Google login is not working. The only fix is to create a new SwitchBot account using an email address and password and ask SwitchBot to transfer your devices.

By all means complain to SwitchBot as I have not had any help from them with this and the issue is on their system.

**Comment by L1ttleP00l** [comment] 2024-07-31 20:56
I take note of this information and thank you for your prompt feedback.

Best regards

Le 31 juil. 2024, 21:34, à 21:34, Adrian Rockall ***@***.***> a écrit:

**Comment by Jan0910** [comment] 2024-08-06 15:29
Same problem here i hope it will fixed fast.

**Comment by AdyRock** [comment] 2024-08-06 16:15
I don't think the Google login will be fixed. I suggest creating a new account with an email address and transfer your devices.

**Comment by Thijs1980** [comment] 2024-08-06 17:04
Thanx!

Op 6 aug 2024 om 18:16 heeft Adrian Rockall ***@***.***> het volgende geschreven:

﻿

I don't think the Google login will be fixed. I suggest creating a new account with an email address and transfer your devices.

**Comment by L1ttleP00l** [comment] 2024-08-07 08:32
Hello,
I have indeed created a new account and no longer have any incidents.
Thank you for your feedback.
Sincerely

**Closed** 2024-09-01 22:21 UTC
